WS2812 Tester: SizeEncoder Class Reference
SizeEncoder Class Reference
The size encoder class.
#include <SizeEncoder.h>
Public Member Functions
SizeEncoder (uint8_t pin_a, uint8_t pin_b, unsigned long ready_time_ms)
Constructor.
~SizeEncoder ()
Destructor.
unsigned long ready_pos ()
Position of the encoder after it is "ready".
unsigned long t_since_last_change ()
Time (ms) since the last encoder change.
bool ready ()
Returns if the encoder is considered "ready" to be read.
bool update ()
Updates the SizeEncoder class. Call this function periodically with high priority!
Private Member Functions
long read_enc ()
Returns the current position of the encoder.
void prep_rdy ()
Prepares rdy and rdy_tstamp.
Private Attributes
Encoder * enc
unsigned long ready_time
unsigned long saved_pos
unsigned long rdy_pos
bool rdy
unsigned long rdy_tstamp
unsigned long last_change_tstamp
Detailed Description
The size encoder class.
The following class is used to handle the rotary encoder which sets the strip size.
Definition at line 41 of file SizeEncoder.h.
Constructor & Destructor Documentation
SizeEncoder()
SizeEncoder::SizeEncoder (uint8_t pin_a, uint8_t pin_b, unsigned long ready_time_ms)
Constructor.
The following constructor receives the A and B pins of the encoder, as well as the time after which the encoder value is considered to be ready to be read (see ready() for more info).
Parameters
uint8_t a_pin The Arduino pin connected to the encoders A pin.
uint8_t b_pin The Arduino number of the B pin.
Definition at line 46 of file SizeEncoder.cpp.
 : enc(new Encoder(pin_a, pin_b)), ready_time(ready_time_ms)
 {
     saved_pos = read_enc();
     rdy_pos = saved_pos;
     prep_rdy();
 };
References prep_rdy(), and read_enc().
Member Function Documentation
prep_rdy()
void SizeEncoder::prep_rdy () private
Prepares rdy and rdy_tstamp.
The following function sets the rdy flag and sets the rdy_tstamp. See the ready() method for more info.
Definition at line 39 of file SizeEncoder.cpp.
 {
     rdy = false;
     rdy_tstamp = millis() + ready_time;
 }
Referenced by SizeEncoder(), and update().
read_enc()
long SizeEncoder::read_enc () inline private
Returns the current position of the encoder.
The following function returns the current position of the rotary encoder. Before returning the position, the read value is shifted by SHFT_CORRECT_ENCODER_STEP_SIZE (see config.h) to ensure the value is returned in steps of 1.
Returns
The current position of the encoder.
Definition at line 33 of file SizeEncoder.cpp.
 {
     return enc->read() >> SHFT_CORRECT_ENCODER_STEP_SIZE;
 }
Referenced by SizeEncoder(), and update().
ready()
bool SizeEncoder::ready ()
Returns if the encoder is considered "ready" to be read.
The following function returns if the rotary encoder is considered "ready". To ensure the firmware can keep up with changes in the rotary encoder, we must ensure that the task of reading the rotary encoder is provided a high priority where no other tasks can interrupt the firmware from registering changes. Typically hardware interrupts can solve this issue, however, since writing to the LED strip requires hardware interrupts to be disabled, just relying in interrupts in itself will still result in rotary encoder changes getting "skipped" (especially as the LED strip size increases as transmissions take longer to reach the end of the strip). Thus, the solution to fix this issue is to halt the firmware from doing anything else than listening for rotary encoder change until the rotary encoder has remained unchaged for a specific ammount of time (See ready_time_ms), after which it is considered "ready" to be read. The drawback of this is that the firmware cannot do anything else in the meantime, which for our application however, is perfectly acceptable.
Returns
If the encoder is considered "ready" to be read
Definition at line 88 of file SizeEncoder.cpp.
 {
     return rdy;
 }
ready_pos()
unsigned long SizeEncoder::ready_pos ()
Position of the encoder after it is "ready".
The following function returns the position of the rotary encoder after it is considered as "ready" (see ready() for more info)
Returns
Position of the encoder after it is considered ready
Definition at line 94 of file SizeEncoder.cpp.
 {
     return rdy_pos;
 }
t_since_last_change()
unsigned long SizeEncoder::t_since_last_change ()
Time (ms) since the last encoder change.
The following function returns the time (in ms) that has passed since the last change of the rotary encoder.
Returns
Time (ms) since last encoder change
Definition at line 100 of file SizeEncoder.cpp.
 {
     return millis() - last_change_tstamp;
 }
update()
bool SizeEncoder::update ()
Updates the SizeEncoder class. Call this function periodically with high priority!
The following function updates the SizeEncoder class. It must be called periodically with high priority, meaning running time consuming tasks should be avoided when calling this function periodically. Violating the priorty requirements of this function will result in sluggish/laggy reading of the encoder.
Returns
If rotary encoder position has changed
Definition at line 61 of file SizeEncoder.cpp.
 {
     bool ret = false;
     long pos = read_enc();
     if (pos < 0) {
         pos = 0;
         enc->write(0);
     }
     bool changed = ((unsigned long) pos != saved_pos);
     if (changed) {
         saved_pos = pos;
         last_change_tstamp = millis();
         ret = true;
         prep_rdy();
     } else if (!rdy) {
         if (millis() >= rdy_tstamp) {
             rdy_pos = pos;
             rdy = true;
         }
     }
     return ret;
 }
References prep_rdy(), and read_enc().
The documentation for this class was generated from the following files:
include/SizeEncoder.h
src/SizeEncoder.cpp