WS2812 Tester: ColorPots Class Reference
ColorPots Class Reference
Provides a hardware abstraction to the color pots.
#include <ColorPots.h>
Public Member Functions
ColorPots (uint8_t pin_r, uint8_t pin_g, uint8_t pin_b)
Constructor for the ColorPots class.
bool update ()
Updates the ColorPots class. Call this function periodically!
bool zeroed ()
Returns if all pots are set to their 0 position.
void get_rgb (uint8_t &r, uint8_t &g, uint8_t &b)
Returns the values of the RGB pots from the last update() call.
unsigned long t_since_last_change ()
Returns the time (ms) since the last change in the RGB pots.
Private Attributes
uint8_t pin_r
uint8_t pin_g
uint8_t pin_b
uint8_t r
uint8_t g
uint8_t b
unsigned long last_change_tstamp
Detailed Description
Provides a hardware abstraction to the color pots.
Definition at line 39 of file ColorPots.h.
Constructor & Destructor Documentation
ColorPots()
ColorPots::ColorPots (uint8_t pin_r, uint8_t pin_g, uint8_t pin_b)
Constructor for the ColorPots class.
The ColorPots constructor takes three potentiometer pins as an argument, initializes the pins to input, and reads the initial potentiometer values.
Parameters
pin_r The pin of the red potentiometer.
pin_g The pin of the green potentiometer.
pin_b The pin of the blue potentiometer.
Definition at line 62 of file ColorPots.cpp.
 : pin_r(pin_r), pin_g(pin_g), pin_b(pin_b)
 {
     pinMode(pin_r, INPUT);
     pinMode(pin_g, INPUT);
     pinMode(pin_b, INPUT);
     update();
     last_change_tstamp = millis();
 }
References update().
Member Function Documentation
get_rgb()
void ColorPots::get_rgb (uint8_t & r, uint8_t & g, uint8_t & b)
Returns the values of the RGB pots from the last update() call.
The following function is used to return the values of the RGB pots from the last update() call.
Parameters
r Receives the fetched red value.
g Receives the fetched green value.
b Receives the fetched blue value.
Definition at line 102 of file ColorPots.cpp.
 {
     r = this->r;
     g = this->g;
     b = this->b;
 }
t_since_last_change()
unsigned long ColorPots::t_since_last_change ()
Returns the time (ms) since the last change in the RGB pots.
The following function is used to return the time (ms) since the last registered change in the RGB pots.
Returns
unsigned long The time (ms) since the last change in the RGB pots.
Definition at line 110 of file ColorPots.cpp.
 {
     return millis() - last_change_tstamp;
 }
update()
bool ColorPots::update ()
Updates the ColorPots class. Call this function periodically!
The following function is used to update the ColorPots class. It should be called periodically and will read the latest values from the potentiometers and check if they have changed from the last call.
Definition at line 73 of file ColorPots.cpp.
 {
     bool ret = false;
     uint8_t _r, _g, _b;
     _r = avg_read_pot(pin_r, AVG_ADC_SAMPLES);
     _g = avg_read_pot(pin_g, AVG_ADC_SAMPLES);
     _b = avg_read_pot(pin_b, AVG_ADC_SAMPLES);
     // Check if any of the values have changed.
     if (_r != r || _g != g || _b != b) {
         last_change_tstamp = millis();
         ret = true;
     }
     r = _r;
     g = _g;
     b = _b;
     return ret;
 }
References avg_read_pot().
Referenced by ColorPots().
zeroed()
bool ColorPots::zeroed ()
Returns if all pots are set to their 0 position.
The following function is used to check if all pots are set to their 0 position.
Returns
bool True if all pots are set to their 0 position, false otherwise.
Definition at line 96 of file ColorPots.cpp.
 {
     return !(r | g | b);
 }
The documentation for this class was generated from the following files:
include/ColorPots.h
src/ColorPots.cpp