WS2812 Tester: Strip Class Reference
Strip Class Reference
The Strip class.
#include <Strip.h>
Public Member Functions
Strip (uint8_t pin)
Constructor for the Strip class.
~Strip ()
Destructor for the Strip class.
void set_n_leds (unsigned long n)
Sets the size/number of leds in the strip.
void set_rgb (uint8_t r, uint8_t g, uint8_t b)
Sets the color of the strip.
unsigned int get_n_leds ()
Gets the currently set size of the strip.
void get_rgb (uint8_t &r, uint8_t &g, uint8_t &b)
Gets the currently set color of the strip.
void update_strip ()
Applies changes to the strip.
Private Attributes
ws2812_cpp * ws2812_dev
ws2812_rgb clr = {0, 0, 0}
unsigned long n_leds = 0
unsigned long prev_n_leds = 0
bool clear_strip = false
Detailed Description
The Strip class.
The following class is used to handle the WS2812 strip.
Definition at line 40 of file Strip.h.
Constructor & Destructor Documentation
Strip()
Strip::Strip (uint8_t pin)
Constructor for the Strip class.
Parameters
uint8_t pin The pin the WS2812 strip is connected to.
Definition at line 59 of file Strip.cpp.
 {
     ws2812_cfg cfg;
     cfg.pins = &pin;
     cfg.n_dev = 1;
     cfg.rst_time_us = WS2812_RESET_TIME;
     cfg.order = WS2812_COLOR_ORDER;
     uint8_t ret = 0;
     ws2812_dev = new ws2812_cpp(cfg, &ret);
     if (ret != 0) {
         Serial.println("Failed to initialize ws2812_cpp, error code: " + String(ret));
         while(true);
     }
 }
Member Function Documentation
get_n_leds()
unsigned int Strip::get_n_leds ()
Gets the currently set size of the strip.
The following function is used to get the currently set (see set_n_leds()) number of leds in the strip.
Returns
unsigned long The currently set number of leds in the strip.
Definition at line 114 of file Strip.cpp.
 {
     return n_leds;
 }
get_rgb()
void Strip::get_rgb (uint8_t & r, uint8_t & g, uint8_t & b)
Gets the currently set color of the strip.
The following function is used to get the currently set (see set_rgb()) color of the strip.
Parameters
r Currently set red value.
g Currently set green value.
b Currently set blue value.
Definition at line 120 of file Strip.cpp.
 {
     r = clr.r;
     g = clr.g;
     b = clr.b;
 }
set_n_leds()
void Strip::set_n_leds (unsigned long n)
Sets the size/number of leds in the strip.
The following function is used to set the size/number of leds in the strip.
Note
You must call update_strip() to apply the changes.
Definition at line 93 of file Strip.cpp.
 {
     prev_n_leds = n_leds;
     n_leds = n;
     // Clear strip if size decreases
     clear_strip = (n_leds < prev_n_leds);
     update_strip();
 }
References update_strip().
set_rgb()
void Strip::set_rgb (uint8_t r, uint8_t g, uint8_t b)
Sets the color of the strip.
Parameters
r Red value.
g Green value.
b Blue value.
Note
You must call update_strip() to apply the changes.
Definition at line 105 of file Strip.cpp.
 {
     clr.r = r;
     clr.g = g;
     clr.b = b;
     update_strip();
 }
References update_strip().
update_strip()
void Strip::update_strip ()
Applies changes to the strip.
The following function applies the changes to the strip. Call it after setting the color or the strip size (or both).
Definition at line 82 of file Strip.cpp.
 {
     if (clear_strip) {
         set_strip(ws2812_dev, 0, 0, 0, prev_n_leds);
         clear_strip = false;
     }
     set_strip(ws2812_dev, clr.r, clr.g, clr.b, n_leds);
 }
References set_strip().
Referenced by set_n_leds(), and set_rgb().
The documentation for this class was generated from the following files:
include/Strip.h
src/Strip.cpp