WS2812 Tester: Display Class Reference
Display Class Reference
Display class.
#include <Display.h>
Public Member Functions
Display (String title_text)
Constructor.
void start_screensaver ()
Starts the screensaver.
void stop_screensaver ()
Stops/Exits the screensaver.
void set_n_leds (unsigned long n)
Sets/Updates the value of the LEDs count.
void set_rgb (uint8_t r, uint8_t g, uint8_t b)
Sets/Updates the values of the RGB information.
void update ()
Updates the display.
Private Member Functions
void screensaver ()
Handles the screensaver.
Private Attributes
bool show_screensaver = false
String title_text
unsigned long n_leds = 0
uint8_t r = 0
uint8_t g = 0
uint8_t b = 0
Adafruit_SSD1306 * display
Detailed Description
Display class.
Definition at line 42 of file Display.h.
Constructor & Destructor Documentation
Display()
Display::Display (String title_text)
Constructor.
The constructor initializes the Adafruit_SSD1306 object, and sets the title text which will be projected on the top of the display.
Parameters
title_text The title text to be projected on the top of the display.
Definition at line 78 of file Display.cpp.
 : title_text(title_text), display(new Adafruit_SSD1306(OLED_WIDTH, OLED_HEIGHT, &Wire, OLED_RESET))
 {
     if(!display->begin(SSD1306_SWITCHCAPVCC, OLED_I2C_ADDRESS)) {
         Serial.println(F("SSD1306 allocation failed"));
         while(true);
     }
 }
Member Function Documentation
screensaver()
void Display::screensaver () private
Handles the screensaver.
The following function handles the Waddle Dee screensaver. It is called periodically by the update() function if the show_screensaver flag is set (See start_screensaver() and stop_screensaver()).
Definition at line 100 of file Display.cpp.
 {
     static bool wait = false;
     static unsigned long wait_until;
     if (wait) {
         wait = millis() < wait_until;
         return;
     }
     display->clearDisplay();
     display->setTextSize(1);
     display->setTextColor(WHITE);
     // Draw credits at top of screen.
     display->setCursor(0,0);
     display->println(SCREEN_SAVER_CREDITS_MSG);
     // Draw Waddle Dee with open eyes
     if (random(0, 100) <= 60) {
         display->drawBitmap(0, 20, WaddleDeeOpen, 128, 64, WHITE);
         wait_until = millis() + SCREEN_SAVER_MIN_EYES_OPEN_TIME;
     }
     // Draw Waddle Dee with closed eyes
     else {
         display->drawBitmap(0, 20, WaddleDeeClosed, 128, 64, WHITE);
         wait_until = millis() + SCREEN_SAVER_MIN_BLINK_TIME;
     }
     wait = true;
     display->display();
 }
Referenced by update().
set_n_leds()
void Display::set_n_leds (unsigned long n)
Sets/Updates the value of the LEDs count.
The following function sets/updates the value of the LEDs count.
Parameters
n Value to set the LEDs count to.
Definition at line 161 of file Display.cpp.
 {
     n_leds = n;
 }
set_rgb()
void Display::set_rgb (uint8_t r, uint8_t g, uint8_t b)
Sets/Updates the values of the RGB information.
The following function sets/updates the values of the RGB information.
Parameters
r Red value to be displayed.
g Green value to be displayed.
b Blue value to be displayed.
Definition at line 167 of file Display.cpp.
 {
     this->r = r;
     this->g = g;
     this->b = b;
 }
start_screensaver()
void Display::start_screensaver ()
Starts the screensaver.
The following function starts the screensaver by setting the show_screensaver flag to true. Once the show_screensaver flag is set, the update() function will call periodically call screensaver() until the show_screensaver flag is set to false (see stop_screensaver()).
Definition at line 88 of file Display.cpp.
 {
     show_screensaver = true;
 }
stop_screensaver()
void Display::stop_screensaver ()
Stops/Exits the screensaver.
The following function exits the screensaver by setting the show_screensaver flag to false.
Definition at line 94 of file Display.cpp.
 {
     show_screensaver = false;
 }
update()
void Display::update ()
Updates the display.
The following function updates the information on the display. It should be called periodically.
Definition at line 135 of file Display.cpp.
 {
     if(show_screensaver) {
         screensaver();
         return;
     }
     display->clearDisplay();
     display->setTextSize(1);
     display->setTextColor(WHITE);
     display->setCursor(0,0);
     display->println(title_text);
     display->setTextSize(2);
     display->setCursor(0, 25);
     display->println(String(F("LEDs: ")) + String(n_leds));
     display->setTextSize(1);
     display->setCursor(0, 50);
     display->println(rgb_to_str(r, g, b));
     display->display();
 }
References rgb_to_str(), and screensaver().
The documentation for this class was generated from the following files:
include/Display.h
src/Display.cpp