WS2812 Tester: src/Display.cpp File Reference
Display.cpp File Reference
Defines functions for the Display class.
#include <config.h>
#include <Display.h>
Functions
String uint8_to_fixed_str (uint8_t n)
Converts a uint8_t to a fixed size string.
String rgb_to_str (uint8_t r, uint8_t g, uint8_t b)
Converts RGB values to a string.
Detailed Description
Defines functions for the Display class.
Author
Patrick Pedersen
The following file defines functions for the Display class. See Display.h for more information.
Definition in file Display.cpp.
Function Documentation
rgb_to_str()
String rgb_to_str (uint8_t r, uint8_t g, uint8_t b)
Converts RGB values to a string.
The following function converts RGB values to a string with the following format: "R:<red> G:<green> B:<blue>"
Parameters
r The red value.
g The green value.
b The blue value.
Returns
The converted RGB values as a string.
Definition at line 68 of file Display.cpp.
 {
     String ret = "";
     ret += "R:" + uint8_to_fixed_str(r) + " ";
     ret += "G:" + uint8_to_fixed_str(g) + " ";
     ret += "B:" + uint8_to_fixed_str(b);
     return ret;
 }
References uint8_to_fixed_str().
Referenced by Display::update().
uint8_to_fixed_str()
String uint8_to_fixed_str (uint8_t n)
Converts a uint8_t to a fixed size string.
The following function converts a uint8_t to a fixed size string. In other words, each number is represented with 3 digits, where zeroes are prepended if necessary (ex. 001, 015 etc.).
Parameters
n The number to convert.
Returns
The converted number as a fixed size string.
Definition at line 44 of file Display.cpp.
 {
     String ret = "";
     if (n < 100)
         ret += "0";
     if (n < 10)
         ret += "0";
     ret += String(n);
     return ret;
 }
Referenced by rgb_to_str().